Repository sandialabs/WecOptTool, pull requests merged in 2022-04, with the labels that each got.

#78 treat bounds separately; scale bounds and initial guess; expose callback arg
  CHANGES.md
  setup.cfg
  tests/test_wecopttool.py
  wecopttool/core.py
Labels: bug, enhancement

#38 Linear PTO
  CHANGES.md
  examples/dev_cases/IEEE_2022/optim_unstructured.ipynb
  examples/dev_cases/IEEE_2022/verification_PI.ipynb
  examples/dev_cases/linear_pto.ipynb
  examples/dev_cases/rm3_geom/rm3_float.stl
  examples/dev_cases/rm3_geom/rm3_spar.stl
  examples/tutorial_1_wavebot.ipynb
  tests/test_wecopttool.py
  wecopttool/core.py
  wecopttool/pto.py
Labels: enhancement

#89 Initial guess, automatic scaling, multi-DOF power limit
  .github/workflows/python-package.yml
  CHANGES.md
  docs/source/theory.rst
  examples/tutorial_1_wavebot.ipynb
  tests/test_wecopttool.py
  wecopttool/core.py
Labels: enhancement

#105 Minor typographic edits in documentation and examples
  docs/source/theory.rst
  examples/tutorial_1_wavebot.ipynb
Labels: documentation
