Repository sandialabs/WecOptTool, pull requests merged in 2022-10, with the labels that each got.

#124 PTO module post-processing, docstrings, typehints
  docs/source/conf.py
  docs/source/theory.rst
  examples/dev_cases/IEEE_2022/optim_unstructured.ipynb
  examples/dev_cases/IEEE_2022/verification_PI.ipynb
  examples/dev_cases/linear_pto.ipynb
  examples/dev_cases/rm3.py
  examples/dev_cases/rm3_geom/rm3_float.stl
  examples/dev_cases/rm3_geom/rm3_spar.stl
  examples/dev_cases/v2_refactor/bem.nc
  examples/dev_cases/v2_refactor/v2_tut1_simple.ipynb
  examples/dev_cases/validation_case_a.py
  examples/dev_cases/wavebot_kinematics.ipynb
  examples/dev_cases/wavebot_reg_irreg_waves.ipynb
  examples/tutorial_1_wavebot.ipynb
  setup.cfg
  tests/test_hydrostatics.py
  tests/test_integration.py
  tests/test_wecopttool_org.py
  wecopttool/__init__.py
  wecopttool/core.py
  wecopttool/geom.py
  wecopttool/hydrostatics.py
  wecopttool/pto.py
  wecopttool/waves.py
Labels: documentation, clean-up

#152 Add freq and period coords to post-proc results
  wecopttool/core.py
  wecopttool/pto.py
Labels: enhancement

#147 imageio v3 interface and pygifsicle optimization for gif animations in docs
  docs/source/make_theory_animations.py
  pyproject.toml
Labels: documentation, upstream

#151 CI/CD improvements
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/RELEASING.md
  .github/pull_request_template.md
  .github/workflows/build-test-doc.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gh-pages.yml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .gitignore
  CHANGES.md
  README.md
  pyproject.toml
  tests/test_hydrostatics.py
  tests/test_waves.py
Labels: enhancement, CI
