Repository sandialabs/WecOptTool, pull requests merged in 2022-02, with the labels that each got.

#41 jupyter-notebook dependency
  CHANGES.md
  README.md
  setup.cfg
Labels: bug

#44 update tutorial 1
  examples/tutorial_1_wavebot.ipynb
  examples/tutorial_2_wavebot_optimization.ipynb
  wecopttool/core.py
Labels: documentation

#45 Tutorial 2 updates
  CHANGES.md
  examples/tutorial_2_wavebot_optimization.ipynb
  wecopttool/core.py
Labels: documentation

#47 Update README
  CHANGES.md
  README.md
Labels: documentation

#55 Constraints
  CHANGES.md
  tests/test_wecopttool.py
  wecopttool/core.py
Labels: bug

#56 fixes #51 WaveBot cross section plot
  CHANGES.md
  examples/tutorial_2_wavebot_optimization.ipynb
  wecopttool/geom.py
Labels: bug

#48 x scale logging
  CHANGES.md
  docs/source/theory.rst
  wecopttool/core.py
Labels: enhancement
