Repository sandialabs/WecOptTool, pull requests merged in 2022-11, with the labels that each got.

#145 NEW FEATURE: improve/fix scipy.minimize interfaces in wec.solve
  tests/test_integration.py
  wecopttool/core.py
Labels: upstream

#159 CLEANUP: hydrostatics `_set_*` functions combined into one
  wecopttool/hydrostatics.py
Labels: clean-up

#161 CI/CD: Improve unit tests.
  .github/workflows/release.yml
  .gitignore
  docs/source/_templates/class.rst
  docs/source/theory.rst
  pyproject.toml
  tests/test_core.py
  tests/test_hydrostatics.py
  tests/test_pto.py
  tests/test_waves.py
  wecopttool/__init__.py
  wecopttool/core.py
  wecopttool/pto.py
  wecopttool/waves.py
Labels: testing
