Repository sandialabs/WecOptTool, pull requests merged in 2022-03, with the labels that each got.

#53 explicit buoyancy/gravity
  CHANGES.md
  docs/source/theory.rst
  examples/tutorial_1_wavebot.ipynb
  examples/tutorial_2_wavebot_optimization.ipynb
  tests/test_wecopttool.py
  wecopttool/core.py
Labels: enhancement

#64 Cleanup type hints + spelling, source API links
  CHANGES.md
  docs/source/theory.rst
  docs/source/tutorials.rst
  examples/tutorial_1_wavebot.ipynb
  examples/tutorial_2_wavebot_optimization.ipynb
  wecopttool/core.py
Labels: documentation

#63 Kinematics
  CHANGES.md
  docs/source/theory.rst
  examples/dev_cases/rm3.py
  examples/dev_cases/validation_case_a.py
  examples/dev_cases/wavebot_kinematics.ipynb
  tests/test_wecopttool.py
  wecopttool/pto.py
Labels: documentation

#71 BUG fix: structured controllers
  CHANGES.md
  setup.cfg
  tests/test_wecopttool.py
  wecopttool/core.py
  wecopttool/pto.py
Labels: bug

#81 added conversion from degrees to radians in core.py and run_bem() so …
  CHANGES.md
  examples/dev_cases/wavebot_reg_irreg_waves.ipynb
  wecopttool/core.py
  wecopttool/waves.py
Labels: bug, good first issue

#85 Check gains against theory
  tests/test_wecopttool.py
Labels: testing
