Repository sandialabs/WecOptTool, pull requests merged in 2023-05, with the labels that each got.

#241 Custom user agent for more DOI links
  docs/source/conf.py
Labels: bug, CI

#169 DOCUMENTATION: frequencies, meshing, copyright
  docs/source/conf.py
  docs/source/implementation.rst
  docs/source/theory.rst
  docs/source/wecopttool_refs.bib
  wecopttool/core.py
  wecopttool/pto.py
Labels: documentation

#240 Tutorial 3 corrections
  .github/workflows/push.yml
  .github/workflows/release.yml
  docs/source/conf.py
  examples/data/tutorial_3_results.nc
  examples/tutorial_2_AquaHarmonics.ipynb
  examples/tutorial_3_LUPA.ipynb
Labels: documentation, clean-up
