Repository sandialabs/WecOptTool, pull requests merged in 2023-04, with the labels that each got.

#218 Waves dataarray
  tests/test_waves.py
  wecopttool/waves.py
Labels: enhancement, clean-up

#220 BUG: specify wavespectra>=3.13
  pyproject.toml
Labels: bug, upstream, CI

#231 Add custom user agent when linking to IEEExplore
  docs/source/conf.py
Labels: CI
