Repository sandialabs/WecOptTool, pull requests merged in 2023-10, with the labels that each got.

#277 Static cases (no optimization). Closes #249
  wecopttool/core.py
Labels: enhancement

#275 Fix CI random failures
  wecopttool/core.py
Labels: bug, CI

#267 Documentation improvements/updates
  .github/CONTRIBUTING.md
  .github/RELEASING.md
  INSTALLATION.md
  README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/references.rst
  docs/source/theory.rst
  docs/source/tutorials.rst
  docs/source/wecopttool_refs.bib
  wecopttool/core.py
Labels: documentation

#271 Control fundamental frequency precision
  wecopttool/core.py
Labels: bug
