Repository sandialabs/WecOptTool, pull requests merged in 2025-04, with the labels that each got.

#408 Sphinx build argument bug fix
  docs/build_docs.py
Labels: bug

#418 Small bugs
  tests/test_core.py
  wecopttool/core.py
Labels: clean-up

#420 Wave phase realization dimension in Datasets
  examples/tutorial_3_LUPA.ipynb
  examples/tutorial_4_Pioneer.ipynb
  tests/test_integration.py
  wecopttool/core.py
  wecopttool/pto.py
  wecopttool/utilities.py
Labels: clean-up

#416 tutorial 1: use updated bem object 'hd'
  examples/tutorial_1_WaveBot.ipynb
Labels: documentation, clean-up

#406 Use class for controllers
  examples/tutorial_1_WaveBot.ipynb
  examples/tutorial_2_AquaHarmonics.ipynb
  examples/tutorial_3_LUPA.ipynb
  examples/tutorial_4_Pioneer.ipynb
  tests/test_integration.py
  tests/test_pto.py
  tests/test_utilities.py
  wecopttool/__init__.py
  wecopttool/controllers.py
  wecopttool/pto.py
Labels: clean-up
